In [1]:
import numpy as np

pts1 = np.array([[10, 20], [30, 40], [50, 60], [80, 20],
                 [90, 70], [40, 90], [70, 50], [20, 70]])

pts2 = np.array([[12, 22], [32, 44], [55, 63], [82, 25],
                 [93, 75], [45, 95], [73, 55], [25, 75]])

N = pts1.shape[0]

A = np.column_stack([
    pts1[:,0] * pts2[:,0], pts1[:,1] * pts2[:,0], pts2[:,0],
    pts1[:,0] * pts2[:,1], pts1[:,1] * pts2[:,1], pts2[:,1],
    pts1[:,0], pts1[:,1], np.ones(N)
])

_, _, Vt = np.linalg.svd(A)
F = Vt[-1].reshape(3, 3)

U, S, Vt2 = np.linalg.svd(F)
S[2] = 0
F_rank2 = U @ np.diag(S) @ Vt2

print("Fundamental Matrix F (rank-2 enforced):")
print(F_rank2)


Fundamental Matrix F (rank-2 enforced):
[[-4.60692980e-05  8.18045627e-03 -2.46094045e-01]
 [-7.56357905e-03 -4.65694837e-05  5.62881551e-01]
 [ 2.54481828e-01 -6.32368877e-01  3.97273899e-01]]
